#Requires -Version 5.1
<#
Scans every *.html file in the repo root (excluding index.html itself),
extracts each page's <title>, and regenerates index.html as a card-grid menu.
Run manually before commit, or let the GitHub Actions workflow run it on push.
#>

param(
    [string]$RepoDir = $PSScriptRoot,
    [string]$Output  = (Join-Path $PSScriptRoot 'index.html')
)

$ErrorActionPreference = 'Stop'

function Get-PageTitle {
    param([string]$Path)
    $text = [System.IO.File]::ReadAllText($Path, [System.Text.Encoding]::UTF8)
    $m = [regex]::Match($text, '<title[^>]*>(.*?)</title>', 'IgnoreCase, Singleline')
    if ($m.Success) {
        $t = $m.Groups[1].Value.Trim() -replace '\s+', ' '
        if ($t) { return $t }
    }
    return [System.IO.Path]::GetFileNameWithoutExtension($Path)
}

function HtmlEscape {
    param([string]$s)
    return ($s -replace '&', '&amp;' -replace '<', '&lt;' -replace '>', '&gt;' -replace '"', '&quot;')
}

$pages = Get-ChildItem -Path $RepoDir -Filter '*.html' -File |
    Where-Object { $_.Name -ne 'index.html' } |
    ForEach-Object {
        [pscustomobject]@{
            File     = $_.Name
            Title    = Get-PageTitle -Path $_.FullName
            Modified = $_.LastWriteTime
        }
    } | Sort-Object Title

$pageCount = $pages.Count

$cards = foreach ($p in $pages) {
    $title = HtmlEscape $p.Title
    $file  = HtmlEscape $p.File
    $mod   = $p.Modified.ToString('yyyy-MM-dd')
    @"
            <a href="$file" class="card group block bg-white rounded-xl border border-slate-200 p-5 shadow-sm hover:shadow-md hover:border-indigo-400 transition">
                <div class="flex items-start justify-between mb-2">
                    <i class="fa-solid fa-file-lines text-indigo-500 text-lg"></i>
                    <span class="text-xs text-slate-400">$mod</span>
                </div>
                <h2 class="text-base font-semibold text-slate-800 group-hover:text-indigo-600 leading-snug mb-1">$title</h2>
                <p class="text-xs text-slate-500 font-mono break-all">$file</p>
            </a>
"@
}

$cardsHtml = $cards -join "`n"

$html = @"
<!DOCTYPE html>
<html lang="zh-Hant">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>頁面索引 / Page Index</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang TC", "Microsoft JhengHei", sans-serif; }
        .card:hover { transform: translateY(-2px); }
    </style>
</head>
<body class="bg-slate-50 text-slate-900 min-h-screen">
    <header class="bg-white border-b border-slate-200">
        <div class="max-w-6xl mx-auto px-6 py-8">
            <div class="flex items-center gap-3 mb-2">
                <i class="fa-solid fa-folder-tree text-indigo-600 text-2xl"></i>
                <h1 class="text-2xl font-bold">頁面索引 <span class="text-slate-400 font-normal">/ Page Index</span></h1>
            </div>
            <p class="text-sm text-slate-500">共 <span class="font-semibold text-slate-700">$pageCount</span> 個頁面</p>
        </div>
    </header>
    <main class="max-w-6xl mx-auto px-6 py-8">
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
$cardsHtml
        </div>
    </main>
    <footer class="max-w-6xl mx-auto px-6 py-6 text-xs text-slate-400">
        Auto-generated by <code class="bg-slate-200 text-slate-600 px-1.5 py-0.5 rounded">build-menu.ps1</code>. Do not edit manually — changes will be overwritten on next build.
    </footer>
</body>
</html>
"@

[System.IO.File]::WriteAllText($Output, $html, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote $Output ($pageCount pages)"
